"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal pytest test. Generated by
`scitex-dev ecosystem write-audit-test`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].
"""


def test_audit_all_for_scitex_tex_returns_none():
    # Arrange
    from scitex_dev.testing import audit_all_for_package
    # Act
    result = audit_all_for_package("scitex-tex")
    # Assert
    assert result is None
